# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Firebase/Messaging'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Example-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-tvOS

  target 'Example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
